name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch full history for better diff analysis
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for package.json changes
      id: package-check
      run: |
        if git diff --name-only origin/main...HEAD | grep -q "package.json\|package-lock.json"; then
          echo "package_changed=true" >> $GITHUB_OUTPUT
        else
          echo "package_changed=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Validate package.json if changed
      if: steps.package-check.outputs.package_changed == 'true'
      run: |
        echo "Package files changed, running additional validation..."
        npm ls --depth=0
        
    - name: Run full test suite
      run: npm run test:run
      
    - name: Check test coverage
      run: npm run test:coverage
      
    - name: Verify build works
      run: npm run build
      
    - name: Comment PR with test results
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const fs = require('fs');
          const testResults = `
          ## 🧪 Test Results
          
          - ✅ Tests completed
          - ✅ Build successful
          - ✅ Code quality checks passed
          
          This PR has been automatically validated.
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: testResults
          });